### PR TITLE
add force option to make soft link in nginx conf

### PR DESCRIPTION
**Pull request by zentahori**
I found that we need force option to make a soft link to /etc/nginx/sites-enabled when the old file already exists.
@dmytro 
Please review.

### CODE REVIEW

**Comment by dmytro** [comment]
In this case it's also helpful to have an `-n` option added, i.e. `ln -nfs ...` . Please see discussion of what `-n` option does: http://superuser.com/questions/81164/why-create-a-link-like-this-ln-nsf

**Comment by zentahori** [comment]
```
-h    If the target_file or target_dir is a symbolic link, do not follow it.  This is most useful
       with the -f option, to replace a symlink which may point to a directory.
-n    Same as -h, for compatibility with other ln implementations.
```

Thanks for the advice. It is helpful.

**Comment by zentahori** [comment]
Please check it.
@dmytro

**Comment by dmytro** [comment]
Thank you. :+1:

**Pull request merged**
