### PR TITLE
add ghost recipe for cms and split existing grunt.rb into 3 parts

### PR DESCRIPTION
**Pull request by zentahori**
This PR includes 3 things.
- 1. Split an existing grunt.rb into 3 parts named bower.rb, npm.rb and  grunt.rb.
- 2. Add a new variable config_sub_dir to search for manifest configs in sub-directories.
- 3. Add ghost.rb for capistrano to create symlink and restart ghost in ghost setup procedure.

@dmytro 
Please review.

### CODE REVIEW

**Comment by dmytro** [comment]
@zentahori 

Thank you. Code looks good. 

Just to clarify, this would require also changes to  `config/deploy/frontend/*`: need to add 
```
recipe [...]
``` 
line for new recipes (replacement for grunt recipe). Correct?

:+1:

**Comment by zentahori** [comment]
@dmytro 
Yes, correct.
After this PR is merged, I will send another PR to enable these changes on Capiche.
These recipes are called from capiche config (config/deploy/cms.rb) shown below.
```
recipe :npm
recipe :bower
recipe :ghost
```

**Comment by dmytro** [comment]
From the maintenance point of view it is, probably, better to include this commit into the Capiche PR. 

git looks at the hash of the commit, not at the PR, i.e. it's not required to merge PR for the upstream reference, only commit and push is enough.

**Comment by zentahori** [comment]
My working tree is different from the original.
Because I don't have the permission to push here dmytro/capistrano-recipes directly,
My working tree under capiche submodule is not updated.
I forked this repository and I did work in the other working directory apart from the upstream working tree : capiche where I have already modified some codes.
So this one needs to be merged, so that I can update my original submodule.
Is there any good way or tips?

**Comment by zentahori** [comment]
Thank you.

**Pull request merged**
